# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Parchment
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.01.19

# Environment Properties

forge_version=1.7.10-10.13.4.1614
forge_version_range=[10.13.4.1614,)
loader_version_range=[4,)

## Mod Properties

mod_id=testing
mod_name=Testing
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.nova.testing
mod_authors=ImVeryBad
mod_description=Testing stuff.